#!/bin/bash

### the script succeeds from test_single.lsf

#BSUB -L /bin/bash
#BSUB -J test_single

#BSUB -u jliu78@mgh.harvard.edu
### -- send notification at start -- 
#BSUB -B 
### -- send notification at completion -- 
#BSUB -N

if [ ! -d "logs" ]; then
	mkdir logs
fi 

#BSUB -e logs/%J-errors.err
#BSUB -o logs/%J-outputs.out

#BSUB -q normal
#BSUB -n 16
#BSUB -R 'rusage[mem=32000]'

cd ~/Documents/herv_project

### raw_data stores all fastq files named as 'fq' or better 'fq.gz' to be processed, it is suggested by siyi to store gzipped fastq files in the raw_data folder
### if raw_data folder has reletive dir as '../raw_data', input value as "raw_data"

### for subread, store in ../hERV_Work the annotation gtf/gff3 files of both transcriptom and ERV, genome fasta 
### for salmon, store in ../hERV_Work the index file named as "$hervname_index", by default it is "package-entities-erv_index"
### and genome fasta and fasta files of transcripts and ervs to be quantified

### the script will identify files as paired when there are two files named  
### file_name= basename theNameOfFastqFile .*
### if [[ ${file_name: -1} = "1" && -e "${file_name::-1}2.fq.gz" ]]; then #if formatted correctly
### 				echo -e "$(basename $file_name),$(basename ${file_name::-1})2" >> $PAIR_FILE

### this lsf is for human data, for mouse data please submit test_single_mouse.lsf, siyi said the scripts will require the name he left in test_single_mouse.lsf

bash main.sh -PLATFORM "cluster-mgh" -ANALYSIS_STEP "all" -SOURCE "raw_data" -BATCH_SIZE 1 -CLEAR_TMP -MAX_PARALLEL 1 

### all output files will be stored in ../hervwork/results

### -MAX_PARALLEL 2


