#BSUB -L /bin/bash
#BSUB -J test_single

#BSUB -u syang39@mgh.harvard.edu
### -- send notification at start -- 
#BSUB -B 
### -- send notification at completion -- 
#BSUB -N

if [ ! -d "logs" ]; then
	mkdir logs
fi 

#BSUB -e logs/%J-errors.err
#BSUB -o logs/%J-outputs.out

#BSUB -q normal
#BSUB -n 1
#BSUB -R 'rusage[mem=1000]'
cd ~/Documents/hERV_project

# REF_ANNOTATION_LOC=${REF_ANNOTATION_LOC}
# REF_GENOME_LOC=${REF_GENOME_LOC}
# hERV_DIR=${hERV_DIR}
# hERV_FILE=${hERV_FILE}
# COMB_ANNOTATION=${COMB_ANNOTATION}
# ANALYSIS_STEP=${ANALYSIS_STEP}
# PLATFORM=${PLATFORM}
# PAIR_FILE=${PAIR_FILE}
# SOURCE_LOC=${SOURCE_LOC}
# CLEAR_TMP=${CLEAR_TMP}
# OVER_WRITE=${OVER_WRITE}
# COUNT_METHOD=${COUNT_METHOD}
# BATCH_NAME=${BATCH_NAME}


bash ${main_loc}/analysis.sh