#!/bin/bash
#BSUB -L /bin/bash
#BSUB -J test_single

#BSUB -u syang39@mgh.harvard.edu
### -- send notification at start -- 
#BSUB -B 
### -- send notification at completion -- 
#BSUB -N

if [ ! -d "logs" ]; then
	mkdir logs
fi 

#BSUB -e logs/%J-errors.err
#BSUB -o logs/%J-outputs.out

#BSUB -q normal
#BSUB -n 16
#BSUB -R 'rusage[mem=24000]'

cd ~/Documents/herv_project

bash main.sh -PLATFORM "cluster-mgh" -ANALYSIS_STEP "all" -SOURCE "raw_data" -BATCH_SIZE 2 -CLEAR_TMP